version: '3.9'

services:
  postgres:
    image: postgres:15
    container_name: quadra_postgres
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: Leonard72@
      POSTGRES_DB: Quadra
    ports:
      - "5433:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  api:
    build:
      context: .
      dockerfile: Quadra.Api/Dockerfile
    container_name: quadra_api
    ports:
      - "8080:80"
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
    depends_on:
      - postgres

volumes:
  postgres_data:
